name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run tests
        run: node --test test/**/*.test.js

      - name: Check code syntax
        run: node --check lib/*.js plugin/*.js bin/*.js
